# Imagen base
FROM node:20.13.1

# Establecer el directorio de trabajo en el contenedor
WORKDIR /inventario

# Copiar los archivos de dependencias primero para aprovechar la cache de Docker
COPY package.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Exponer el puerto
EXPOSE 3002

# El comando para ejecutar la aplicación
CMD ["node", "src/index.js"]
