version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/
        read_only: true
    networks:
      - webRestaurant

  usuarios:
    image: blwmi/usuarios
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - webRestaurant

  inventario:
    image: blwmi/inventario
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - webRestaurant

  facturas:
    image: blwmi/facturas
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - webRestaurant

  web:
    image: blwmi/webpicco
    ports:
      - "2080:80"
    depends_on:
      - usuarios
      - inventario
      - facturas
    networks:
      - webRestaurant

  transferencia:
    image: blwmi/transferencia
    depends_on:
      - db
    networks:
      - webRestaurant
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: proyecto

networks:
  webRestaurant:
